# Generated by Django 3.1.4 on 2021-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='disease_infection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
