# Generated by Django 3.2 on 2021-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Hospital',
        ),
        migrations.AddField(
            model_name='order',
            name='Hospital',
            field=models.ManyToManyField(to='hospital.Hospital'),
        ),
    ]
